apiVersion: v1
kind: Service
metadata:
  name: gatling-solr
  namespace: {{ .Values.namespace }}
  labels:
    app: gatling-solr
spec:
  ports:
    - port: 80
      name: gatling-solr
  selector:
    app: gatling-solr